---
- hosts: ansible-server
  become: true

  tasks:
  - name: create docker image using war file
    command: docker build -t simple-devops-image:latest .
    args:
      chdir: /opt/k8s-lab

  - name: create tag to image
    command:  docker tag simple-devops-image tenzindorji/simple-devops-image

  - name: Log into DockerHub
    docker_login:
      username: ****
      password: ***@1

  - name: push image on to dockerhub
    command:  docker push tenzindorji/simple-devops-image

  - name: remove docker images form ansible server
    command:  docker rmi simple-devops-image:latest tenzindorji/simple-devops-image
    ignore_errors: yes
