---
- name: create service for deployment
  hosts: kubernetes-master
 # become: true
  user: root #it even works with root user. 

  tasks:
  - name: create a service
    command: kubectl apply -f valaxy-service.yml
